# Generated by Django 2.0.9 on 2018-11-02 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_group', models.CharField(max_length=1)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IndustrySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_sector', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SicCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sic_code', models.CharField(blank=True, max_length=4)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siccodes.Industry')),
                ('industry_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siccodes.IndustryGroup')),
                ('industry_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siccodes.IndustrySector')),
            ],
        ),
        migrations.AddField(
            model_name='industrygroup',
            name='industry_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siccodes.IndustrySector'),
        ),
        migrations.AddField(
            model_name='industry',
            name='industry_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siccodes.IndustryGroup'),
        ),
    ]
