# Generated by Django 2.0.9 on 2018-10-26 18:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('group_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustrySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('sector_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1)])),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siccodes.IndustryGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MajorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('major_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='industrygroup',
            name='major_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siccodes.MajorGroup'),
        ),
    ]
