# Generated by Django 2.0.9 on 2018-10-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siccodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrygroup',
            name='group_number',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='sector_number',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='majorgroup',
            name='major_number',
            field=models.CharField(max_length=2),
        ),
    ]
