# Generated by Django 2.0.9 on 2018-10-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siccodes', '0003_siccode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siccode',
            old_name='group_number',
            new_name='industry_group',
        ),
        migrations.RenameField(
            model_name='siccode',
            old_name='sector_number',
            new_name='industry_sector',
        ),
        migrations.RenameField(
            model_name='siccode',
            old_name='major_number',
            new_name='major_group',
        ),
    ]
