# Generated by Django 2.0.9 on 2018-11-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siccodes', '0004_auto_20181026_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siccode',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
